# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks: []

builds:
  - id: kudet
    env:
      - CGO_ENABLED=0
    main: .
    binary: "{{ .Env.KUDET_BINARY_FILENAME }}"
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm64

archives:
  - id: kudet
    builds:
      - kudet
    files:
      - "*THIS_FILE_DOES_NOT_EXIST*"
    name_template: kudet_{{ .Version }}_{{ .Os }}_{{ .Arch }}

nfpms:
  - id: deb-and-rpm-packages
    package_name: kudet
    homepage: https://kurtosistech.com
    description: "Install (Ku)rtosis (De)veloper (T)ools - Kudet"
    vendor: Kurtosis Technologies Inc.
    builds:
      - kudet
    formats:
      - deb
      - rpm
    maintainer: Kurtosis Technologies Inc. <hello@kurtosistech.com>
  - id: apk-package
    package_name: kudet
    homepage: https://kurtosistech.com
    description: "Install (Ku)rtosis (De)veloper (T)ools - Kudet"
    vendor: Kurtosis Technologies Inc.
    builds:
      - kudet
    formats:
      - apk
    maintainer: Kurtosis Technologies Inc. <hello@kurtosistech.com>

brews:
  - name: kudet
    ids:
      - kudet
    tap:
      owner: kurtosis-tech
      name: homebrew-tap
    commit_author:
      name: kurtosisbot
    commit_msg_template: "Automated formula update for Kudet, version {{ .Tag }}"
    homepage: "https://www.kurtosistech.com"
    description: "Kudet - (Ku)rtosis (De)veloper (T)ools"

    # One day, we'll probably want to put a license
    # license: SOME-SPDX-LICENSE

    # NOTE: Goreleaser *should* automatically detect the binaries packaged inside the archives being installed by the Homebrew formula, but it doesn't due to:
    #  https://github.com/goreleaser/goreleaser/issues/2488
    # When this is fixed, we can remove this section
    install: |
      bin.install "kurtosis"

release:
    github:
      owner: kurtosis-tech
      name: kudet-release-artifacts

    ids:
      - kudet
      - kudet-linux-packages

publishers:
  - name: fury.io
    ids:
      - deb-and-rpm-packages
    dir: "{{ dir .ArtifactPath }}"
    env:
      # This will get set by CI; see the CI config for how
      - 'FURY_TOKEN={{ .Env.FURY_TOKEN }}'
    cmd: "curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/kurtosis-tech/"

source:
  enabled: false

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Env.VERSION }}"
changelog:
  # We manage our own changelog
  skip: true
