version: 2.1

executors:
  ubuntu_vm:
    machine:
      image: ubuntu-2004:202201-02

parameters:
  goreleaser-version:
    type: string
    default: "v1.9.1"

jobs:
  build_kudet:
    docker:
      - image: "goreleaser/goreleaser:<< pipeline.parameters.goreleaser-version >>"
    resource_class: large
    steps:
      - checkout
      # The 'git config' and 'go env' steps are to allow Go to read modules from our private Github repos
      # The KURTOSISBOT_GITHUB_TOKEN is a secret provided at CI build time

      # Cache our dependencies
      - restore_cache:
          keys:
            - << pipeline.parameters.cli-build-cache-key-prefix >>-{{ checksum "cli/go.sum" }}

      - run: |
          git config --global url."https://${KURTOSISBOT_GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
          go env -w "GOPRIVATE=github.com/kurtosis-tech/*"
          cli/scripts/build.sh
      - save_cache:
          key: << pipeline.parameters.cli-build-cache-key-prefix >>-{{ checksum "cli/go.sum" }}
          paths:
            - "/go/pkg/mod"   # Go module cache for the Goreleaser image, as reported by "go env GOMODCACHE"
            - "/root/.cache/go-build"    # Go build cache for the Goreleaser image, as reported by "go env GOCACHE"

      - persist_to_workspace:
          root: .
          paths:
            - "./<< pipeline.parameters.cli-dist-home-relative-dirpath >>"

  push_kudet_artifacts:
    docker:
      - image: "goreleaser/goreleaser:<< pipeline.parameters.goreleaser-version >>"
    steps:
      - checkout
      # The 'git config' and 'go env' steps are to allow Go to read modules from our private Github repos
      # The KURTOSISBOT_GITHUB_TOKEN is a secret provided at CI build time
      - run: |
          git config --global url."https://${KURTOSISBOT_GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
          go env -w "GOPRIVATE=github.com/kurtosis-tech/*"
          cli/scripts/build.sh true

  workflows:
    - kurtosis-docs-checker/check-docs:
        markdown-link-check-config-json: "{}"
        filters:
          branches:
            ignore:
              - develop
              - master
    - build_cli:
        context:
          - github-user
        filters:
          branches:
            ignore:
              - develop
              - master
    - push_cli_artifacts:
        context:
          - github-user
          - gemfury-publisher
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^[0-9]+\.[0-9]+\.[0-9]+$/